### ISSUE TITLE
Theemo Figma plugin can be slow

### ISSUE THREAD

**Issue by ChucKN0risK** [theemo-tokens/figma-theemo#40]
Hi @gossi,

First of all, thanks for your work on Theemo 🙏 

We're using it internally at Specify to handle our Light and Dark themes and it works like a charm. We've even been evangelizing it [to our users community](https://www.figma.com/file/jTzVNLbtK5eFjUrP3EAm6z/Global-and-Alias-styles-in-Figma?node-id=222%3A2).

We've had some feedback about its slowness though when some Figma frames are containing many layers or when teams have a large amount of tokens. The plugin was sometimes unusable during 6/7 seconds of lag.

They found that disabling the "Auto Update Styles References" to make it work again.

Would you have an idea of the possible reasons making the plugin slow and potential solutions to fix this?

Thanks in advance ✌️

**Comment by gossi** [comment]
Done in #57
