### ISSUE TITLE
How to use library styles as origin?

### ISSUE THREAD

**Issue by garthwalker** [theemo-tokens/figma-theemo#43]
Hi, your documentation mentions that it's possible

> It still is possible to use library styles, then you can't use the style references manage dialog, instead manually assign those style and THEN use the theemo dialog in order to persist it.

However, I can't figure out how to do it. Can you please clarify how to manually assign and then persist?

**Comment by gossi** [comment]
Now Figma provided variables, which allow referencing variables from another file, so I'm closing.
